version: "3"

services:
  app1:
    build: ./app1
    volumes:
      - ./core:/app/core
    environment:
      - PORT=8000
    command: gunicorn --bind 0.0.0.0:8000 app:app

  app2:
    build: ./app2
    volumes:
      - ./core:/app/core
    environment:
      - PORT=8000
    command: gunicorn --bind 0.0.0.0:8000 app:app

  app3:
    build: ./app3
    volumes:
      - ./core:/app/core
    environment:
      - PORT=8000
    command: gunicorn --bind 0.0.0.0:8000 app:app

  nginx:
    image: nginx:latest
    ports:
      - "5001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
